### ISSUE TITLE
Script stops after 40 Subscriptions, Fetch error

### ISSUE THREAD

**Issue by hermify** [KennethWussmann/youtube-subscription-sync-cli#191]
Hi,
script is subscribing about 20 channels. Then i get the error:

`(node:49082) UnhandledPromiseRejectionWarning: FetchError: request to https://youtube.googleapis.com/youtube/v3/subscriptions?part=snippet failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/youtube-subscription-sync-cli/bin/index.js:133:26464)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:49082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:49082) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

It continues with 20 channels but then stops continuing.

**Comment by hermify** [comment]
So the error of fetching the subscription leads to a loop. 

Plus: Is there a check, if the channel has already been subscribed? If the channel is already subscribed, Console puts out "Failed to subscribe...". 


**Insert is causing the Error:**
<img width="927" alt="Bildschirmfoto 2023-02-17 um 11 14 09" src="https://user-images.githubusercontent.com/22779096/219616555-fde79712-d3cc-4150-b356-8877d8d93dfd.png">

The method is not stopping, it is continuing calling the insert API.
<img width="1122" alt="Bildschirmfoto 2023-02-17 um 11 18 40" src="https://user-images.githubusercontent.com/22779096/219617329-4142e028-8c44-4eb4-ae1a-82106bd0abea.png">



**The Contingent has been full**
<img width="1024" alt="Bildschirmfoto 2023-02-17 um 01 10 04" src="https://user-images.githubusercontent.com/22779096/219616582-7a937928-726c-4ef7-a5fb-e53b4a20dc43.png">

**Costs for an API Call:**
<img width="800" alt="Bildschirmfoto 2023-02-17 um 11 16 02" src="https://user-images.githubusercontent.com/22779096/219616711-3c34f7bb-0fdb-4907-93b5-6a47af39e681.png">

**Comment by KennethWussmann** [comment]
Hey @hermify,
Thanks for reporting this issue. 
With #192, I added that the CLI would first also fetch all the current subscriptions of the target account, so it only tries to subscribe to channels it's not already subscribed to. 
That should save a little bit of quota, but unfortunately, with the default quota of 10000 units, one would only be able to subscribe to ~199 channels a day.

A new version, 1.2.0 was just released with this adjustment.
